# -*- coding: utf-8 -*-
"""punto 1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UkvBdoPLCRm4hlV0yK4kME_fUDC7H-r4
"""

def palindromo(palabra): # Función
  lista = [] # Lista para la palabra
  lista_al_revez = [] # Lista de la palabra al revez
  for n in palabra: # Ciclo for
    lista.append(n) # Agregamos las letras con append a la lista
    lista_al_revez.insert(0, n) # Insertamos las letras de la apalabra al revez, agregandolas en la primera posición
  if lista == lista_al_revez: # Ciclo if para probar si son iguales
    return True # Devuelve que la palabra es palíndromo
  else: # En caso de que no sea igual
    return False # Devuelve que la palabra no es palíndromo

if __name__ == "__main__": # EL MAIN
  palabra = input("Ingresa la palabra que desees comprobar: ") # Usuario ingresa palabra
  prim = palindromo(palabra) #Ejecutar función
  if prim == True: # En caso de que sea palindromo la palabra
    print(str(palabra) +" es un palíndromo") # Imprimir si es un palíndromo
  else: # En caso de que no sea palindroma
    print(str(palabra) +" no es un palíndromo") # Imprime que no es un palíndromo