# -*- coding: utf-8 -*-
"""punto 1.4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9xTwokEnO0UILeKDU_3UD4fJSEtRFt7
"""

def sum_may(datos, lista): # Función
  sum_ma = 0 # Variable de suma mayor
  variable_1 = 0 # Primera variable
  variable_2 = 0 # Segunda variable
  for i in range(datos-1): # Ciclo for que recorre la cantidad de datos de la lista
    suma = lista[i] + lista[i+1] # Suma el primer elemento mas el siguiente
    if suma > sum_ma: # Si la suma de los dos datos es mayor a las sumas previas
      sum_ma = suma # Reemplaza el valor
      variable_1 = lista[i] # Reempñaza la variable del primer elemento
      variable_2 = lista[i +1] # Reempñaza la variable del segundo elemento
    else:
      continue # Si no es igual continua
  return sum_ma, variable_1, variable_2 # Retorna las 3 variables


if __name__ == "__main__": # Función main
  datos = int(input("Ingresa el número de datos que deseas agregar: ")) # Ingrese el número de datos que quiere agregar
  lista = [] # Lista vacia
  for n in range(datos): # Ciclo for para agregar el número de datos
    numero = int(input("Ingresa el número: ")) # # Ingresa el entero
    lista.append(numero) # Agregarlo a la lista
  print("Esta es tu lista de números: \n"+ str(lista)) # Imprime la lista
  suma_mayor, numero_1, numero_2 = sum_may(datos, lista) # Ejecutar la función
  print("La mayor suma entre datos consecutivos es "+ str(suma_mayor) +" que es dado por: "+ str(numero_1) +" y "+ str(numero_2) ) # Imprimir resultado