# -*- coding: utf-8 -*-
"""punto 1.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fnQDDg8m0tSeFPUHV7wpU8lUgvlJ14pd
"""

def primos(lista): # Función
  lista_primos = [] # Lista de primos
  for i in lista: # Recorrer los elemntos de la lista
    if i == 1: # SI el elemento es 1
      continue # Continua porque 1 no es primo
    elif i == 2: # Si es 2
      lista_primos.append(i) # El 2 al ser primo lo agregamos
      continue
    else: # En caso de que no sea ni 1 ni 2
      dato = 2 # Inicia en 2, porque ya descartamos el uno y el dos
      contador = 0 # El contador para saber si es primo o no
      while dato < i: # Mientras la variable dato sea menor al número
        if i % dato == 0: # Si la división no da residuo quiere decir que no es primo
          dato = dato + 1 # Aumentamos en uno el dato
          contador = contador + 1 # Aumentamos el contador
        else:
          dato = dato + 1 # Aumentamos en uno el dato
      if contador == 0: # Si no es 0 es primo ya que ningún número lo dividio
        lista_primos.append(i) # Lo agrega a la lista de los primos
      else: # No es primo siguiente número
        continue
  return lista_primos # Devuelva la lista

if __name__ == "__main__": # Función main
  datos = int(input("Ingresa el número de datos que deseas agregar: ")) # Ingrese el número de datos que quiere agregar
  lista = [] # Lista vacia
  for n in range(datos): # Ciclo for para agregar el número de datos
    numero = int(input("Ingresa el número: ")) # # Ingresa el entero
    lista.append(numero) # Agregarlo a la lista
  print("Esta es tu lista de números: \n"+ str(lista)) # Imprime la lista
  nums_p = primos(lista) # Ejecutar función
  print("Estos son los números primos: \n"+ str(nums_p)) # Imprimir lista de primos