# -*- coding: utf-8 -*-
"""punto 1.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uXIMkVyR8z-5i0-Cecf6OPT6AWZ_fF-3
"""

def operaciones(numero_1: float, numero_2: float): # Función
  print("QUE OPERACIÓN DESEAS REALIZAR, SEGUN ESO PON EL SIGNO ASOCIADO \n+ = Suma \n- = Resta \n* = Multiplicación \n/ = División (Número 1 / Número 2) \n// = División Entera (Número 1 // Número 2)") #Explicación por si alguien no lo tiene claro
  eleccion = input("Ingresa la operación que quieras asociada a su número: ")
  bandera = True # Booleano para ciclo
  while bandera == True: #Ciclo usado para que en caso de que el usuario ingrese algo incorrecto en la opreación el codigo no falle sino explique que pasa
    if eleccion == "+": # Si ingreso suma
      print("ENTRADA: ("+ str(numero_1) +", "+ str(numero_2) +", "+ str(eleccion) +")")
      return(numero_1 + numero_2) # Retorna operación de los dos números
    elif eleccion == "-": # Si ingreso resta
      print("ENTRADA: ("+ str(numero_1) +", "+ str(numero_2) +", "+ str(eleccion) +")")
      return(numero_1 - numero_2) # Retorna operación de los dos números
    elif eleccion == "*": # Si ingreso multiplicación
      print("ENTRADA: ("+ str(numero_1) +", "+ str(numero_2) +", "+ str(eleccion) +")")
      return(numero_1 * numero_2) # Retorna operación de los dos números
    elif eleccion == "/": # Si ingreso división
      print("ENTRADA: ("+ str(numero_1) +", "+ str(numero_2) +", "+ str(eleccion) +")")
      return(numero_1 / numero_2) # Retorna operación de los dos números
    elif eleccion == "//": # Si ingreso división entera
      print("ENTRADA: ("+ str(numero_1) +", "+ str(numero_2) +", "+ str(eleccion) +")")
      return(numero_1 // numero_2) # Retorna operación de los dos números
    else: # Caso que sea diferente
      print("Lo siento, ingresaste una opereación incorrecta") # Enseña que cometió un erorr
      eleccion = int(input("Ingresa la operación que quieras asociada a su número")) # Repite el ingreso del dato

if __name__ == "__main__": # Función Main
  numero_1 = float(input("Ingresa un número: ")) # Ingresar primer número
  numero_2 = float(input("Ingressa tu segundo número: ")) # Ingresar segundo número
  resultado = operaciones(numero_1, numero_2) # Ejecutamos la función
  print("Salida= ("+ str(resultado) +")") # Imprimir resultado de la función